#!/usr/bin/env python3
"""Sync the shared functional icon sprite into every page (stdlib only).

The icons are a vendored subset of Lucide (see images/icons/lucide, ISC/MIT).
Rather than duplicate a big sprite by hand across the pages -- or inject it at
runtime and couple the visuals to JavaScript -- this script writes one inline
<svg class="icon-sprite"> block into each page, delimited by ICON-SPRITE markers.
Pages only carry <svg class="icon"><use href="#icon-x"></use></svg>.

Usage: python3 scripts/sync_icon_sprite.py
Idempotent: re-running rewrites the generated block in place.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

PAGES = [
    "404.html", "beta.html", "datenschutz.html", "impressum.html", "index.html",
    "kernel.html", "philosophy.html", "status.html", "team.html", "waitlist.html",
]

# Lucide 1.48.0 inner markup, one <symbol> per icon. Keep in sync with
# images/icons/lucide/*.svg and the SOURCE.txt note there.
SYMBOLS = [
    '<symbol id="icon-arrow-left" viewBox="0 0 24 24"><path d="m12 19-7-7 7-7"/><path d="M19 12H5"/></symbol>',
    '<symbol id="icon-arrow-right" viewBox="0 0 24 24"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></symbol>',
    '<symbol id="icon-calendar-clock" viewBox="0 0 24 24"><path d="M16 14v2.2l1.6 1"/><path d="M16 2v3"/><path d="M21 7.338V5a2 2 0 00-2-2H5a2 2 0 00-2 2v14a2 2 0 002 2h2.338"/><path d="M3 9h5.859"/><path d="M8 2v3"/><circle cx="16" cy="16" r="6"/></symbol>',
    '<symbol id="icon-check" viewBox="0 0 24 24"><path d="M20 6 9 17l-5-5"/></symbol>',
    '<symbol id="icon-clock" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></symbol>',
    '<symbol id="icon-external-link" viewBox="0 0 24 24"><path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/></symbol>',
    '<symbol id="icon-mail" viewBox="0 0 24 24"><path d="m22 7-8.991 5.727a2 2 0 0 1-2.009 0L2 7"/><rect x="2" y="4" width="20" height="16" rx="2"/></symbol>',
    '<symbol id="icon-menu" viewBox="0 0 24 24"><path d="M4 5h16"/><path d="M4 12h16"/><path d="M4 19h16"/></symbol>',
    '<symbol id="icon-pause" viewBox="0 0 24 24"><rect x="14" y="3" width="5" height="18" rx="1"/><rect x="5" y="3" width="5" height="18" rx="1"/></symbol>',
    '<symbol id="icon-play" viewBox="0 0 24 24"><path d="M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z"/></symbol>',
    '<symbol id="icon-x" viewBox="0 0 24 24"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></symbol>',
]

START = "<!-- ICON-SPRITE:START (generated by scripts/sync_icon_sprite.py; do not edit by hand) -->"
END = "<!-- ICON-SPRITE:END -->"
BLOCK = (
    START + "\n<svg class=\"icon-sprite\" aria-hidden=\"true\" focusable=\"false\">\n"
    + "\n".join("  " + s for s in SYMBOLS)
    + "\n</svg>\n" + END
)

SKIP_LINK = re.compile(r'(<a class="skip-link"[^>]*>.*?</a>)', re.S)
EXISTING = re.compile(re.escape("<!-- ICON-SPRITE:START") + r".*?" + re.escape(END), re.S)


def main() -> int:
    for name in PAGES:
        path = ROOT / name
        text = path.read_text(encoding="utf-8")
        if "<!-- ICON-SPRITE:START" in text:
            text = EXISTING.sub(lambda _: BLOCK, text)
        else:
            match = SKIP_LINK.search(text)
            if not match:
                print(f"error: no skip link found in {name}", file=sys.stderr)
                return 1
            text = text[:match.end()] + "\n\n" + BLOCK + text[match.end():]
        path.write_text(text, encoding="utf-8")
        print(f"synced {name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
